 const Data = [{
         "id": 1,
         "index": 0,
         "CategoryImg": "./img/Icons/Frame-1.png",
         "CategoryName": "Account & Finance",
         "jobs": "300 Jobs Available",
         "jobIcon": "./Logo/netflix-4 1.png",
         "jobName": "Netflix",
         "jobCategory": "Senior Product Designer",
         "R": "Remote",
         "F": "Full-Time",
         "location": "Dhaka, Bangladesh",
         "locationIcon": "./img/Icons/Location Icon.png",
         "salary": "100k-200k",
         "salaryIcon": "./img/Icons/Frame.png",
         "phone": "01321068459",
         "phoneIcon": "./img/Icons/Frame-2.png",
         "email": "shantokumar096@gmail.com",
         "emailIcon": "./img/Icons/Frame-3.png",
         "JobDescription": "A UI/UX (User Interface/User Experience) designer is responsible for designing and creating engaging and effective interfaces for software and web applications. This includes designing the layout, visual design, and interactivity of the user interface.",
         "JobResponsibility": "Collaborating with cross-functional teams: UI/UX designers often work closely with other teams, including product management, engineering, and marketing, to ensure that the user interface is aligned with business and technical requirements. You will need to be able to effectively communicate your design ideas and gather feedback from other team members.",
         "EducationalRequirements": "Bachelor degree to complete any reputational university.",
         "Experiences": "2-3 Years in this field."

     },
     {
         "id": 2,
         "index": 1,

         "CategoryImg": "./img/Icons/accounts 1.png",
         "CategoryName": "Creative Design",
         "jobs": "100+ Jobs Available",
         "jobIcon": "./Logo/google-1-1 1.png",
         "jobName": "Google LLC",
         "jobCategory": "Technical Database Engineer",
         "R": "Remote",
         "F": "Full-Time",
         "location": "Dhaka, Bangladesh",
         "locationIcon": "./img/Icons/Location Icon.png",
         "salary": "100k-150k",
         "salaryIcon": "./img/Icons/Frame.png",
         "phone": "01321068459",
         "phoneIcon": "./img/Icons/Frame-2.png",
         "email": "shantokumar096@gmail.com",
         "emailIcon": "./img/Icons/Frame-3.png",
         "JobDescription": "A UI/UX (User Interface/User Experience) designer is responsible for designing and creating engaging and effective interfaces for software and web applications. This includes designing the layout, visual design, and interactivity of the user interface.",
         "JobResponsibility": "Collaborating with cross-functional teams: UI/UX designers often work closely with other teams, including product management, engineering, and marketing, to ensure that the user interface is aligned with business and technical requirements. You will need to be able to effectively communicate your design ideas and gather feedback from other team members.",
         "EducationalRequirements": "Bachelor degree to complete any reputational university.",
         "Experiences": "2-3 Years in this field."
     },
     {
         "id": 3,
         "index": 2,
         "CategoryImg": "./img/Icons/business 1.png",
         "CategoryName": "Marketing & Sales",
         "jobs": "200 Jobs Available",
         "jobIcon": "./Logo/tesla-9 1.png",
         "jobName": "Tesla",
         "jobCategory": "Technical Database Engineer",
         "R": "Remote",
         "F": "Full-Time",
         "location": "Dhaka, Bangladesh",
         "locationIcon": "./img/Icons/Location Icon.png",
         "salary": "100k-150k",
         "salaryIcon": "./img/Icons/Frame.png",
         "phone": "01321068459",
         "phoneIcon": "./img/Icons/Frame-2.png",
         "email": "shantokumar096@gmail.com",
         "emailIcon": "./img/Icons/Frame-3.png",
         "JobDescription": "A UI/UX (User Interface/User Experience) designer is responsible for designing and creating engaging and effective interfaces for software and web applications. This includes designing the layout, visual design, and interactivity of the user interface.",
         "JobResponsibility": "Collaborating with cross-functional teams: UI/UX designers often work closely with other teams, including product management, engineering, and marketing, to ensure that the user interface is aligned with business and technical requirements. You will need to be able to effectively communicate your design ideas and gather feedback from other team members.",
         "EducationalRequirements": "Bachelor degree to complete any reputational university.",
         "Experiences": "2-3 Years in this field."

     },
     {
         "id": 4,
         "index": 3,
         "CategoryImg": "./img/Icons/chip 1.png",
         "CategoryName": "Engineering job",
         "jobs": "200+ Jobs Available",
         "jobIcon": "./Logo/google-1-1 1-1.png",
         "jobName": "Google llc",
         "jobCategory": "Softer Engineer",
         "R": "Remote",
         "F": "Full-Time",
         "location": "Dhaka, Bangladesh",
         "locationIcon": "./img/Icons/Location Icon.png",
         "salary": "100k-500k",
         "salaryIcon": "./img/Icons/Frame.png",
         "phone": "01321068459",
         "phoneIcon": "./img/Icons/Frame-2.png",
         "email": "shantokumar096@gmail.com",
         "emailIcon": "./img/Icons/Frame-3.png",
         "JobDescription": "A UI/UX (User Interface/User Experience) designer is responsible for designing and creating engaging and effective interfaces for software and web applications. This includes designing the layout, visual design, and interactivity of the user interface.",
         "JobResponsibility": "Collaborating with cross-functional teams: UI/UX designers often work closely with other teams, including product management, engineering, and marketing, to ensure that the user interface is aligned with business and technical requirements. You will need to be able to effectively communicate your design ideas and gather feedback from other team members.",
         "EducationalRequirements": "Bachelor degree to complete any reputational university.",
         "Experiences": "2-3 Years in this field."
     }
 ]

 export default Data